### ISSUE TITLE
想下载下来看看，但github的下载速度。。。。慢的让人绝望

### ISSUE THREAD

**Issue by JinYanjie** [joe1206/The-Economist#1]

**Comment by joe1206** [comment]
这个是百度云群组，可以先进去




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JinYanjie <notifications@github.com&gt;
发送时间: 2020年6月12日 12:30
收件人: joe1206/The-Economist <The-Economist@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[joe1206/The-Economist] 想下载下来看看，但github的下载速度。。。。慢的让人绝望 (#1)

**Comment by JinYanjie** [comment]
没看到链接
